name: mqtt_gateway
description: An implementation of an MQTT Gateway as an A2A agent
version: 1.0.0
repository: https://github.com/shamblett/a2a-dart-samples/agents/MQTTGateway
publish_to: none
funding:
  - https://www.darticulate.com/#funding

environment:
  sdk: '>=3.9.0 <4.0.0'

dependencies:
    colorize: '^3.0.0'
    a2a: '^3.0.0'
    mqtt_client: '^10.11.1'


dev_dependencies:
  lints: '^6.0.0'
  test: '^1.26.3'
